"""Qualification requirements for kvnloo/cua#31.

Rows say which evidence a mechanism still needs. They do not record a run
that did not happen, and a historical green result does not certify a later head.
"""

from __future__ import annotations


def qualification_rows() -> list[dict[str, object]]:
    return [
        {
            "mechanism": "visual routing",
            "upstream": "4196",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": True,
            "historical_green_certifies": False,
            "evidence_on_this_host": "live visual path not measured",
            "missing_machine": "macOS and Windows",
        },
        {
            "mechanism": "verifier screenshot projection",
            "upstream": "4164",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": False,
            "historical_green_certifies": False,
            "evidence_on_this_host": "call site only; walker log not captured",
            "missing_machine": "macOS and Windows",
        },
        {
            "mechanism": "observation provenance",
            "upstream": "4009",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": False,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": False,
            "historical_green_certifies": False,
            "evidence_on_this_host": "field absent from this checkout; generator commands not run",
            "missing_machine": "",
        },
        {
            "mechanism": "passive native observation",
            "upstream": "3904",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": True,
            "historical_green_certifies": False,
            "evidence_on_this_host": "caller vectors only",
            "missing_machine": "macOS",
        },
        {
            "mechanism": "caller guarded run",
            "upstream": "5",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": False,
            "one_platform_sufficient": True,
            "all_supported_platforms_required": False,
            "final_desktop_e2e_required": False,
            "historical_green_certifies": False,
            "evidence_on_this_host": "caller negatives recorded; wall time not measured",
            "missing_machine": "",
        },
        {
            "mechanism": "mechanical batch freshness",
            "upstream": "2794",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": True,
            "historical_green_certifies": False,
            "evidence_on_this_host": "caller stale-target fixture; native app trace not captured",
            "missing_machine": "Windows",
        },
        {
            "mechanism": "cancellation ownership",
            "upstream": "3796",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": False,
            "final_desktop_e2e_required": False,
            "historical_green_certifies": False,
            "evidence_on_this_host": "request-issuance order recorded; held input not in the probe",
            "missing_machine": "macOS",
        },
        {
            "mechanism": "conditional observation",
            "upstream": "18",
            "unit_only_sufficient": False,
            "deterministic_fixture_required": True,
            "native_producer_trace_required": True,
            "one_platform_sufficient": False,
            "all_supported_platforms_required": True,
            "final_desktop_e2e_required": False,
            "historical_green_certifies": False,
            "evidence_on_this_host": "one GTK trace; false negatives were not measured",
            "missing_machine": "macOS and Windows",
        },
    ]
